version: 0.1

phases:
    install:
        commands:
            - echo Nothig to do in the install phase...
    pre_build:
        commands:
            - echo Nothing to do in the pre_build phase...
    build:
        commands:
            - echo $CODEBUILD_SOURCE_VERSION
            - echo "******** Uploading to S3 ********"
            - aws s3 sync src/ s3://free-domain-test.tk/game_id_00000003/
    post_build:
        commands:
            - echo Build completed on `date`

