phases:
    install:
        commands:
            - echo Nothig to do in the install phase...
    pre_build:
        commands:
            - echo Nothing to do in the pre_build phase...
    build:
        commands:
            - echo "******** Uploading to S3 ********"
            - aws s3 sync / s3://free-domain-test.tk/game_id_00000003/master/
    post_build:
        commands:
            - echo Build completed on `date`
