version: 0.2

env:
    parameter-store:
        GAME_ID: 00000003
        CH:master

phases:
    install:
        commands:
            - echo Nothig to do in the install phase...
    pre_build:
        commands:
            - echo Nothing to do in the pre_build phase...
    build:
        commands:
            - echo "******** Uploading to S3 ********"
            - aws s3 sync src/ s3://free-domain-test.tk/game_id_$GAME_ID/$CH
    post_build:
        commands:
            - echo Build completed on `date`

